### PR TITLE
parse nested fields from cursor field value

### PR DESCRIPTION
**Pull request by Danny02**
Hi,

I have documents in Elastic with the following structure:
```json
{
  "searchProps": {
    "latestUpdate": "2022-10-25T06:21:10.891414"
   }
  "document": {...}
}
```

I think that I am able to use your connector with the changes of this PR.

P.S. I think the default cursor field `_id` used in `ElasticRepository` is wrong, because you pass the document id in the document Map<String, Object> as `es-id`.

### CODE REVIEW

**Comment by DarioBalinzo** [comment]
Hi @Danny02 , thanks for the PR. I will check this during the next days!

**Comment by Danny02** [comment]
Some updates:
- I had to update Mockito (minor version) to make it run with Java > 8. I can not download Java 8 anymore and couldn't run the tests locally otherwise
- I noticed that the cursor is also used in other places

**Comment by Danny02** [comment]
I also have some problems with the conversion of my data to a Struct. I'm debugging this also.

**Review by DarioBalinzo — APPROVED** [review]
Thanks again for this. I lked your solution with `CursorField` class.

**Comment by DarioBalinzo** [comment]
Do you usually download the relase from this repo or from the confluent hub?

In few days I will draft a new release in this repo, and after that I will ask confluent to update also their hub.

**Pull request merged**
