### PR TITLE
Feature/44/add elastic ssl config

### LINKED ISSUE #44: NumberFormatException  for es.host  while starting Elasticsearch source connector
Hi
I am getting below error when I start connector. 
Please help on this. Its running but Cant see any desired topic in kafka. 

[2021-05-12 16:30:42,611] INFO ElasticSourceConnectorConfig values: 
	batch.max.rows = 10000
	connection.attempts = 3
	connection.backoff.ms = 10000
	es.host = "myhost.uat.com"
	es.password = "myEspass"
	es.port = "9200"
	es.scheme = http
	es.user = "elastic"
	fieldname_converter = avro
	filters.json_cast = null
	filters.whitelist = null
	incrementing.field.name = "@timestamp_log"
	index.prefix = "my_index-*"
	mode = 
	poll.interval.ms = 5000
	topic.prefix = "myprefix_"
 (com.github.dariobalinzo.ElasticSourceConnectorConfig:347)
[2021-05-12 16:30:42,611] ERROR WorkerConnector{id=elasticsearch-source} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector:119)
java.lang.NumberFormatException: For input string: ""9200""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:638)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.github.dariobalinzo.ElasticSourceConnector.start(ElasticSourceConnector.java:63)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:253)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:293)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:209)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)
[2021-05-12 16:30:42,614] INFO Finished creating connector elasticsearch-source (org.apache.kafka.connect.runtime.Worker:269)
[2021-05-12 16:30:42,615] INFO Skipping update of connector elasticsearch-source since it is not running

### PR DESCRIPTION
**Pull request by DarioBalinzo**
Work in progress, resolves #44

### CODE REVIEW

**Comment by kyriakos96** [comment]
Hi @DarioBalinzo Any progress on this? Did you manage to get this up and running?

Thank you very much for all the effort.

**Comment by DarioBalinzo** [comment]
Hi @kyriakos96 , the change should be almost done. 
I need to perform some integration tests before releasing a new version, however you can build and try this draft branch just to perform a check.

the new configuration is:
es.tls.keystore.location
es.tls.keystore.password
es.tls.truststore.location
es.tls.truststore.password

I am very busy these days for personal reasons, but as the feature is in high demand I will try my best to finish testing in the next few days.

**Comment by nmousouros** [comment]
Hi @DarioBalinzo, We've build and tested this, it works as expected. 

The keystore is not really necessary if you just want to trust a certificate. 

Thank you so much!

**Comment by kyriakos96** [comment]
> Hi @kyriakos96 , the change should be almost done.
> I need to perform some integration tests before releasing a new version, however you can build and try this draft branch just to perform a check.
> 
> the new configuration is:
> es.tls.keystore.location
> es.tls.keystore.password
> es.tls.truststore.location
> es.tls.truststore.password
> 
> I am very busy these days for personal reasons, but as the feature is in high demand I will try my best to finish testing in the next few days.

Thank you @DarioBalinzo for this. Looks good so far. Will keep you updated. Thank you

**Comment by DarioBalinzo** [comment]
Happy to hear that! 
I will complete also my checks and update the documentation, and then this branch will be released as a new stable version.

**Comment by DarioBalinzo** [comment]
I'm merging the branch into 1.4.2 and releasing the compiled binaries (version 1.4.2). 
Enjoy!

**Comment by DarioBalinzo** [comment]
Resolves also #47

**Pull request merged**
